.PHONY: build
run:
	tt build

.PHONY: start
run:
	tt start dialogs

.PHONY: stop
stop:
	tt stop dialogs

.PHONY: restart
restart:
	tt stop restart

.PHONY: status
status:
	tt status

.PHONY: clean
clean:
	tt clean -f
