version: '3.9'

services:
  pg-0:
    image: bitnami/postgresql-repmgr:15
    restart: always
    environment:
      - POSTGRESQL_DATABASE=hlsoc
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - POSTGRESQL_SYNCHRONOUS_REPLICAS_MODE=FIRST
      - POSTGRESQL_MAX_CONNECTIONS=1000
      - REPMGR_PASSWORD=postgres
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    ports:
      - "5433:5432"
    volumes:
      - pg_0_data:/bitnami/postgresql
  pg-1:
    image: bitnami/postgresql-repmgr:15
    restart: always
    environment:
      - POSTGRESQL_DATABASE=hlsoc
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - POSTGRESQL_SYNCHRONOUS_REPLICAS_MODE=FIRST
      - POSTGRESQL_MAX_CONNECTIONS=1000
      - REPMGR_PASSWORD=postgres
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    ports:
      - "5434:5432"
    volumes:
      - pg_1_data:/bitnami/postgresql
  pg-2:
    image: bitnami/postgresql-repmgr:15
    restart: always
    environment:
      - POSTGRESQL_DATABASE=hlsoc
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
      - POSTGRESQL_SYNCHRONOUS_REPLICAS_MODE=FIRST
      - POSTGRESQL_MAX_CONNECTIONS=1000
      - REPMGR_PASSWORD=postgres
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
    ports:
      - "5435:5432"
    volumes:
      - pg_2_data:/bitnami/postgresql
  pgpool:
    image: bitnami/pgpool:4
    ports:
      - "5432:5432"
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432,2:pg-2:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=postgres
      - PGPOOL_ADMIN_PASSWORD=postgres
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
      - PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT=yes
      - PGPOOL_ENABLE_LOG_HOSTNAME=yes
      - PGPOOL_MAX_POOL=1000
    healthcheck:
      test: [ "CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - pg-0
      - pg-1
      - pg-2
  migrate:
    image: migrate/migrate
    volumes:
      - ./postgres/migrations:/postgres/migrations
    command: [ "-path", "/postgres/migrations", "-database", "postgres://postgres:postgres@pgpool:5432/hlsoc?sslmode=disable", "up" ]
    depends_on:
      pgpool:
        condition: service_healthy
  serve:
    build: .
    env_file:
      - path: .env
        required: false
    ports:
      - "9090:9090"
    environment:
      - GRPC_ADDR=:9090
    depends_on:
      - pgpool
      - migrate
      - rabbitmq
      - redis
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
  pg_2_data:
    driver: local
  redis_data:
    driver: local